### ISSUE TITLE
Misleading benchmark results

### ISSUE THREAD

**Issue by sp00x** [astro/node-expat#161]
I'm just a bit curious about the benchmark results.

Comparing libxmljs which builds a full DOM structure to just passing something on to expat without even hooking up event handlers - isn't that a bit unfair?

I.e. a SAX parser without even processing the nodes can't be considered doing the same work as a DOM parser is doing?

**Comment by astro** [comment]
Does `new libxml.SaxPushParser()` really construct expensive DOM nodes? If so, this would need to be fixed in our benchmark.

**Comment by sp00x** [comment]
@astro Sorry - I am probably wrong then - did not realize there was a SAX parser in libxml also.. :Ø

I was using the DOM parser in libxmljs, which a bit surprisingly gave me better performance than when I rewrote the parsing using expat.

I even tried multiple times to optimize my rather simple document parsing, but I narrowed it down to mostly relating to string trimming in post-processing, which I had to do with expat since it does not support ignoring whitespace for text.

Is there no whitespace ignore option with expat?

**Comment by astro** [comment]
> I was using the DOM parser in libxmljs, which a bit surprisingly gave me better performance than when I rewrote the parsing using expat.

They probably build the DOM in native code...

> Is there no whitespace ignore option with expat?

No, there is no such option. You need to ignore it in your JS code.
