### ISSUE TITLE
Is there any chance node-expat will support xpath syntax?

### ISSUE THREAD

**Issue by tuananh** [astro/node-expat#163]
`libxmljs` is able to do this. I was wondering if node-expat can do the same?

```
var gchild = xmlDoc.get('//grandchild');

console.log(gchild.text());  // prints "grandchild content"
```

**Comment by astro** [comment]
node-expat is just about parsing. ltx can create a DOM-like tree for you. Please have a look at https://github.com/dodo/ltx-xpath
