### ISSUE TITLE
AWS Lambda registration

### ISSUE THREAD

**Issue by barrct** [astro/node-expat#173]
As there is no "install" process when using Amazon's Serverless functionality and it runs data from what has been zipped up, all packages need to be installed before it's pushed up.
That's typically not an issue unless you have to compile some c++ for a specific server.
Luckily AWS is nice enough to let everyone know what Lambda runs on.
http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

So, spin up an AWS EC2 instance based on the current AMI that is used for Lambda, install node, python, gcc and install node-expat? Sure, everything compiles fine.
Take that package, require it and test nothing more than a basic require in Lambda and we fail.
{
  "errorMessage": "Module did not self-register.",
  "errorType": "Error",
  "stackTrace": [
    "Object.Module._extensions..node (module.js:434:18)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "bindings (/var/task/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)",
    "Object.<anonymous> (/var/task/node_modules/node-expat/lib/node-expat.js:4:32)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)"
  ]
}

It seems that the internet's basic fix is to rm -rf node_modules and reinstall it. Well, that doesn't help. I'm lost as to what's failing but something isn't working and I have no idea where to go from here.
Any ideas to try out?

It's quite easy to test, spin up an ec2 instance, install node-expat and push your code to lambda.

**Comment by barrct** [comment]
I'm sorry, totally my fault. When I installed node from yum I expected it to be v4 or v6 but it was v0.10 so of course nothing worked.
If anyone else needs to run node-expat in Lambda, check your version of node when compiling.

**Comment by steltz** [comment]
@barrct I'm having issues running this package as a dependency of another package I'm using in my Lambda function. Can you help me out?

I've tried using both v6.10.0 and v8.10.0. When trying both versions, I've deleted my Lambda function, confirmed my node version using nvm, ran npm install, then uploaded my .zip file to Lambda using the serverless framework.
