### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [astro/node-expat#175]
Hi!

This repository bundles an outdated vulnerable copy of Expat 2.2.0. Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you! 

Best

&nbsp;
Sebastian

**Comment by lovell** [comment]
Please see #176
