### ISSUE TITLE
Is there a way to get empty-element tags with attributes 

### ISSUE THREAD

**Issue by Sudeepa14** [astro/node-expat#183]
Example :  <w:pStyle w:val="Hangingindent"/> , This tag is considered a "startElement" as well as a "endElement" by the API

**Comment by danielecr** [comment]
Is there someone who can close this, please?
@Sudeepa14 if not sure, close this yourself. Please, consider that `startElement` event is fired _before_ the `endElement` when the parser see an empty tag, and `startElement` callback has (String name, Object attr) parameters.
So, nothing special here.

And the test is in
https://github.com/astro/node-expat/blob/master/test/index.js#L96
(or is this a kind of advertising for tuananh sax-parser? well, use github as you want, but I do not like you guys)
