### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by mezgaAladar** [astro/node-expat#191]
Hello,
Since the latest update (2.3.17) I got the same access error in both machines (used it as a dependency for node-osm-stream version 0.2.2 on Ubuntu machines):

> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '<GLOBALPATH>'

**Comment by exse2** [comment]
Try

npm install node-expat --verbose --unsafe-perm=true
