### ISSUE TITLE
Node 14 update

### ISSUE THREAD

**Issue by JeremyTX** [astro/node-expat#207]
Hi,

I noticed this PR from a year ago to support node 12: https://github.com/astro/node-expat/pull/196. I was wondering if there was a similar one planned for the latest node 14 lts release or if you have any steps and advice for what it would take to open a PR against this repo. Thank you.

**Comment by xamgore** [comment]
I believe @Y-- is the chief here now.

**Comment by Y--** [comment]
Started this PR https://github.com/astro/node-expat/pull/208
Please let me know what you think, happy to work on any feedbacks.

**Comment by Y--** [comment]
PR Merged => closing.

**Comment by xamgore** [comment]
I have been using it with node 15 for a while, seems working to me.
